version: '3.8'

services:
  qualitec-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qualitec-catalogo
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - NUXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
      - NUXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
