-- SQL Schema to initialize the catalog tables in a new Supabase project

-- 1. Create table category_assets
CREATE TABLE IF NOT EXISTS public.category_assets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text UNIQUE NOT NULL,
  cover_image_url text,
  cover_image_blob bytea, -- kept for compatibility, will be null for R2 assets
  color_hex text DEFAULT '#005db7',
  created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS for category_assets
ALTER TABLE public.category_assets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.category_assets FOR SELECT TO public USING (true);
CREATE POLICY "Allow authenticated modifications" ON public.category_assets FOR ALL TO authenticated USING (true);

-- 2. Create table pdf_settings
CREATE TABLE IF NOT EXISTS public.pdf_settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text UNIQUE NOT NULL,
  orientation text DEFAULT 'portrait',
  title_font_size text DEFAULT '36px',
  title_position_y text DEFAULT '0px',
  image_position text DEFAULT 'right',
  card_layout_order text DEFAULT 'specs-first',
  font_size_specs text DEFAULT '10px',
  divider_line_color text DEFAULT '#cbd5e1',
  product_spacing text DEFAULT '24px',
  product_image_offset_y text DEFAULT '0px',
  product_image_offset_x text DEFAULT '0px',
  pdf_image_scale numeric DEFAULT 1.0,
  pdf_image_scale_x numeric DEFAULT 1.0,
  pdf_image_scale_y numeric DEFAULT 1.0,
  card_offset_x text DEFAULT '0px',
  card_offset_y text DEFAULT '0px',
  card_title_offset_x text DEFAULT '0px',
  card_title_offset_y text DEFAULT '0px',
  card_title_font_family text DEFAULT 'Inter',
  card_title_bold boolean DEFAULT false,
  card_title_italic boolean DEFAULT false,
  card_title_underline boolean DEFAULT false,
  card_model_font_size text DEFAULT '24px',
  card_model_offset_x text DEFAULT '0px',
  card_model_offset_y text DEFAULT '0px',
  card_model_font_family text DEFAULT 'Inter',
  card_model_bold boolean DEFAULT false,
  card_model_italic boolean DEFAULT false,
  card_model_underline boolean DEFAULT false,
  tag_font_family text DEFAULT 'Inter',
  tag_font_size text DEFAULT '10px',
  tag_bold boolean DEFAULT false,
  tag_italic boolean DEFAULT false,
  tag_underline boolean DEFAULT false,
  tag_offset_x text DEFAULT '0px',
  tag_offset_y text DEFAULT '0px',
  title_font_family text DEFAULT 'Inter',
  title_bold boolean DEFAULT false,
  title_italic boolean DEFAULT false,
  title_underline boolean DEFAULT false,
  specs_font_family text DEFAULT 'Inter',
  specs_bold boolean DEFAULT false,
  specs_italic boolean DEFAULT false,
  specs_underline boolean DEFAULT false,
  specs_label_width text DEFAULT '45%',
  specs_value_width text DEFAULT '55%',
  specs_padding_y text DEFAULT '4px',
  specs_line_style text DEFAULT 'dashed',
  specs_line_color text DEFAULT '#cbd5e1',
  layout_settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS for pdf_settings
ALTER TABLE public.pdf_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.pdf_settings FOR SELECT TO public USING (true);
CREATE POLICY "Allow authenticated modifications" ON public.pdf_settings FOR ALL TO authenticated USING (true);

-- 3. Create table pdf_templates
CREATE TABLE IF NOT EXISTS public.pdf_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  html_content text,
  css_content jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS for pdf_templates
ALTER TABLE public.pdf_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.pdf_templates FOR SELECT TO public USING (true);
CREATE POLICY "Allow authenticated modifications" ON public.pdf_templates FOR ALL TO authenticated USING (true);

-- 4. Create table products
CREATE TABLE IF NOT EXISTS public.products (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text NOT NULL,
  name_code text NOT NULL,
  category text NOT NULL,
  image text,
  image_blob bytea, -- kept for compatibility, will be null for R2 assets
  datasheet_name text,
  datasheet_blob bytea, -- kept for compatibility, will be null for R2 assets
  datasheet_url text,
  tag text DEFAULT 'NOVO',
  tag_color_class text DEFAULT 'text-[#005db7]',
  bg_class text DEFAULT 'bg-secondary',
  layout_slots integer DEFAULT 3,
  specs jsonb DEFAULT '[]'::jsonb,
  image_scale numeric DEFAULT 1.0,
  image_offset_x numeric DEFAULT 0.0,
  image_offset_y numeric DEFAULT 0.0,
  model3d_url text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS for products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON public.products FOR SELECT TO public USING (true);
CREATE POLICY "Allow authenticated modifications" ON public.products FOR ALL TO authenticated USING (true);
