-- Criar tabela daily_runs para registro da rotina diária
CREATE TABLE IF NOT EXISTS public.daily_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numeral INT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Habilitar RLS e definir políticas de permissão
ALTER TABLE public.daily_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir insercao em daily_runs" ON public.daily_runs
    FOR INSERT TO public, anon, authenticated, service_role WITH CHECK (true);

CREATE POLICY "Permitir leitura em daily_runs" ON public.daily_runs
    FOR SELECT TO public, anon, authenticated, service_role USING (true);
